# Generated by Django 4.0 on 2021-12-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='answer_text',
            field=models.TextField(default=' '),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
