# Generated by Django 4.0 on 2021-12-26 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_poll_answer_text_delete_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='answer_text',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='question_text',
            new_name='question',
        ),
    ]
